### Listar Usuarios ###
GET https://localhost:7134/api/usuario/operacional/listar

### Criar Usuario ###
POST https://localhost:7134/api/usuario/gerencial/cadastrar
Content-Type: application/json

{
    "nome": "Barbara",
    "login": "barbara",
    "senha" : "1234",
    "datanascimento" : "22/08/1996",
    "logado" : false
}

###Alterar###
PUT https://localhost:7134/api/usuario/gerencial/alterar
Content-Type: application/json

{
    "nome": "Barbara",
    "login": "barbara",
    "senha" : "1234",
    "datanascimento" : "22/08/1996",
    "logado" : false
}


###Deletar###
DELETE https://localhost:7134/api/usuario/deletar/2


